spring.application.name=todo.app.maven

# DB接続設定
spring.datasource.url=jdbc:mysql://localhost/todo_app
spring.datasource.username=todo
spring.datasource.password=kaos6991
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# メッセージ設定
spring.messages.basename=messages/messages
spring.messages.encoding=UTF-8